
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTERSLAVE_H
#define MASTERSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MasterSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MasterSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

extern UNS8 MasterSlave_iam_a_slave;
/* Master node data struct */
extern CO_Data MasterSlave_Data;

extern UNS8 Sys_IDNum;		    /* 机型ID                     Mapped at index 0x2000, subindex 0x02 */
extern UNS8 Sys_COVersion;		/* 协议版本                    Mapped at index 0x2000, subindex 0x01 */
extern UNS8 Sys_RunState;		/* 系统运行状态                Mapped at index 0x2000, subindex 0x03 */
extern UNS8 Sys_ModeEn;		    /* 系统控制模式                Mapped at index 0x2000, subindex 0x04 */
extern UNS8 Sys_CtrlLogicEn;	/* 系统控制开关量（标志位）     Mapped at index 0x2000, subindex 0x05 */
extern UNS8 Sys_Load ;		    /* 系统负荷百分比              Mapped at index 0x2000, subindex 0x06 */
extern UNS8 Sys_Type ;		    /* 水系统类型                  Mapped at index 0x2000, subindex 0x07 */
extern UNS8 Sys_Mode ;		    /* 系统控制模式                Mapped at index 0x2000, subindex 0x08 */
extern UNS8 Sys_CtrlLogic ;		/* 系统控制开关量              Mapped at index 0x2000, subindex 0x09 */
extern UNS16 SysTime_Year ;		/* 系统时间年                  Mapped at index 0x2001, subindex 0x01 */
extern UNS8 SysTime_Month ;		/* 系统时间月                  Mapped at index 0x2001, subindex 0x02 */
extern UNS8 SysTime_Day ;	    /* 系统时间日                  Mapped at index 0x2001, subindex 0x03 */
extern UNS8 SysTime_Week ;		/* 系统时间星期                Mapped at index 0x2001, subindex 0x04 */
extern UNS8 SysTime_Hour;		/* 系统时间时                  Mapped at index 0x2001, subindex 0x05 */
extern UNS8 SysTime_Min;		/* 系统时间分                  Mapped at index 0x2001, subindex 0x06 */
extern UNS8 SysTime_Sec;		/* 系统时间秒                  Mapped at index 0x2001, subindex 0x07 */

extern UNS8 MonTmr_OnHour1;		/* 星期一定时1开时间（时）       Mapped at index 0x2002, subindex 0x01 */
extern UNS8 MonTmr_OnMin1;		/* 星期一定时1开时间（分）       Mapped at index 0x2002, subindex 0x02 */
extern UNS8 MonTmr_OffHour1;	/* 星期一定时1关时间（时）       Mapped at index 0x2002, subindex 0x03 */
extern UNS8 MonTmr_OffMin1;		/* 星期一定时1关时间（分）       Mapped at index 0x2002, subindex 0x04 */
extern UNS8 MonTmr_OnHour2;		/* 星期一定时2开时间（时）       Mapped at index 0x2002, subindex 0x05 */
extern UNS8 MonTmr_OnMin2;		/* 星期一定时2开时间（分）       Mapped at index 0x2002, subindex 0x06 */
extern UNS8 MonTmr_OffHour2;    /* 星期一定时2关时间（时）       Mapped at index 0x2002, subindex 0x07 */
extern UNS8 MonTmr_OffMin2;		/* 星期一定时2关时间（分）       Mapped at index 0x2002, subindex 0x08 */

extern UNS8 TueTmr_OnHour1;		/* 星期二定时1开时间（时）       Mapped at index 0x2003, subindex 0x01 */
extern UNS8 TueTmr_OnMin1;		/* 星期二定时1开时间（分）        Mapped at index 0x2003, subindex 0x02 */
extern UNS8 TueTmr_OffHour1;	/* 星期二定时1关时间（时）       Mapped at index 0x2003, subindex 0x03 */
extern UNS8 TueTmr_OffMin1;		/* 星期二定时1关时间（分）       Mapped at index 0x2003, subindex 0x04 */
extern UNS8 TueTmr_OnHour2;		/* 星期二定时2开时间（时）      Mapped at index 0x2003, subindex 0x05 */
extern UNS8 TueTmr_OnMin2;		/* 星期二定时2开时间（分）        Mapped at index 0x2003, subindex 0x06 */
extern UNS8 TueTmr_OffHour2;		/* 星期二定时2关时间（时）        Mapped at index 0x2003, subindex 0x07 */
extern UNS8 TueTmr_OffMin2;		/* 星期二定时2关时间（分）         Mapped at index 0x2003, subindex 0x08 */

extern UNS8 WedTmr_OnHour1;		/* 星期三定时1开时间（时）           Mapped at index 0x2004, subindex 0x01 */
extern UNS8 WedTmr_OnMin1;		/* 星期三定时1开时间（分）         Mapped at index 0x2004, subindex 0x02 */
extern UNS8 WedTmr_OffHour1;	/* 星期三定时1关时间（时）         Mapped at index 0x2004, subindex 0x03 */
extern UNS8 WedTmr_OffMin1 ;	/* 星期三定时1关时间（分）           Mapped at index 0x2004, subindex 0x04 */
extern UNS8 WedTmr_OnHour2;		/* 星期三定时2开时间（时）            Mapped at index 0x2004, subindex 0x05 */
extern UNS8 WedTmr_OnMin2;		/* 星期三定时2开时间（分）           Mapped at index 0x2004, subindex 0x06 */
extern UNS8 WedTmr_OffHour2;	/* 星期三定时2关时间（时）          Mapped at index 0x2004, subindex 0x07 */
extern UNS8 WedTmr_OffMin2;		/* 星期三定时2关时间（分）          Mapped at index 0x2004, subindex 0x08 */

extern UNS8 ThursTmr_OnHour1;	/* 星期四定时1开时间（时）       Mapped at index 0x2005, subindex 0x01 */
extern UNS8 ThursTmr_OnMin1;		/* 星期四定时1开时间（分）             Mapped at index 0x2005, subindex 0x02 */
extern UNS8 ThursTmr_OffHour1;	/* 星期四定时1关时间（时）           Mapped at index 0x2005, subindex 0x03 */
extern UNS8 ThursTmr_OffMin1;	/* 星期四定时1关时间（分）           Mapped at index 0x2005, subindex 0x04 */
extern UNS8 ThursTmr_OnHour2;	/* 星期四定时2开时间（时）           Mapped at index 0x2005, subindex 0x05 */
extern UNS8 ThursTmr_OnMin2;	/* 星期四定时2开时间（分）               Mapped at index 0x2005, subindex 0x06 */
extern UNS8 ThursTmr_OffHour2;	/* 星期四定时2关时间（时）           Mapped at index 0x2005, subindex 0x07 */
extern UNS8 ThursTmr_OffMin2;	/* 星期四定时2关时间（分）                    Mapped at index 0x2005, subindex 0x08 */
 
extern UNS8 FriTmr_OnHour1 ;	/* 星期五定时1开时间（时）             Mapped at index 0x2006, subindex 0x01 */
extern UNS8 FriTmr_OnMin1;		/* 星期五定时1开时间（分）             Mapped at index 0x2006, subindex 0x02 */
extern UNS8 FriTmr_OffHour1;	/* 星期五定时1关时间（时）             Mapped at index 0x2006, subindex 0x03 */
extern UNS8 FriTmr_OffMin1;		/* 星期五定时1关时间（分）             Mapped at index 0x2006, subindex 0x04 */
extern UNS8 FriTmr_OnHour2;		/* 星期五定时2开时间（时）             Mapped at index 0x2006, subindex 0x05 */
extern UNS8 FriTmr_OnMin2;		/* 星期五定时2开时间（分）              Mapped at index 0x2006, subindex 0x06 */
extern UNS8 FriTmr_OffHour2;	/* 星期五定时2关时间（时）              Mapped at index 0x2006, subindex 0x07 */
extern UNS8 FriTmr_OffMin2;		/* 星期五定时2关时间（分）              Mapped at index 0x2006, subindex 0x08 */

extern UNS8 SatTmr_OnHour1;		/* 星期六定时1开时间（时）               Mapped at index 0x2007, subindex 0x01 */
extern UNS8 SatTmr_OnMin1;		/* 星期六定时1开时间（分）               Mapped at index 0x2007, subindex 0x02 */
extern UNS8 SatTmr_OffHour1;	/* 星期六定时1关时间（时）               Mapped at index 0x2007, subindex 0x03 */
extern UNS8 SatTmr_OffMin1;		/* 星期六定时1关时间（分）               Mapped at index 0x2007, subindex 0x04 */
extern UNS8 SatTmr_OnHour2;		/* 星期六定时2开时间（时）               Mapped at index 0x2007, subindex 0x05 */
extern UNS8 SatTmr_OnMin2;		/* 星期六定时2开时间（分）               Mapped at index 0x2007, subindex 0x06 */
extern UNS8 SatTmr_OffHour2;	/* 星期六定时2关时间（时）               Mapped at index 0x2007, subindex 0x07 */
extern UNS8 SatTmr_OffMin2;		/* 星期六定时2关时间（分）               Mapped at index 0x2007, subindex 0x08 */
 
extern UNS8 SunTmr_OnHour1;		/* 星期日定时1开时间（时）               Mapped at index 0x2008, subindex 0x01 */
extern UNS8 SunTmr_OnMin1;		/* 星期日定时1开时间（分）               Mapped at index 0x2008, subindex 0x02 */
extern UNS8 SunTmr_OffHour1;    /* 星期日定时1关时间（时）               Mapped at index 0x2008, subindex 0x03 */
extern UNS8 SunTmr_OffMin1;		/* 星期日定时1关时间（分）               Mapped at index 0x2008, subindex 0x04 */
extern UNS8 SunTmr_OnHour2;		/* 星期日定时2开时间（时）               Mapped at index 0x2008, subindex 0x05 */
extern UNS8 SunTmr_OnMin2;		/* 星期日定时2开时间（分）               Mapped at index 0x2008, subindex 0x06 */
extern UNS8 SunTmr_OffHour2;	/* 星期日定时2关时间（时）               Mapped at index 0x2008, subindex 0x07 */
extern UNS8 SunTmr_OffMin2;		/* 星期日定时2关时间（分）               Mapped at index 0x2008, subindex 0x08 */

extern UNS8 TmrEn_WeekSel;		/* 星期定时开选择                       Mapped at index 0x2009, subindex 0x01 */
extern UNS8 TmrEn_MonAndTue;	/* 星期一星期二定时开关选择              Mapped at index 0x2009, subindex 0x02 */
extern UNS8 TmrEn_WedAndThurs;	/* 星期三星期四定时开关选择              Mapped at index 0x2009, subindex 0x03 */
extern UNS8 TmrEn_FriAndSat;	/* 星期五星期六定时开关选择              Mapped at index 0x2009, subindex 0x04 */
extern UNS8 TmrEn_Sun;		    /* 星期天定时开关选择                   Mapped at index 0x2009, subindex 0x05 */

extern INTEGER16 Sensor_CHWST;		/* 冷冻总管供水温度                Mapped at index 0x200A, subindex 0x01 */
extern INTEGER16 Sensor_CHWRT;		/* 冷冻总管回水温度                Mapped at index 0x200A, subindex 0x02 */
extern INTEGER16 Sensor_CHWSP;		/* 冷冻总管供水压力                Mapped at index 0x200A, subindex 0x03 */
extern INTEGER16 Sensor_CHWRP;		/* 冷冻总管回水压力                Mapped at index 0x200A, subindex 0x04 */
extern INTEGER16 Sensor_CWST;		/* 冷却总管供水温度                Mapped at index 0x200A, subindex 0x05 */
extern INTEGER16 Sensor_CWRT;		/* 冷却总管回水温度                Mapped at index 0x200A, subindex 0x06 */
extern INTEGER16 Sensor_CHWFL;		/* 冷冻总管回水流速                Mapped at index 0x200A, subindex 0x07 */
extern INTEGER16 Sensor_CWFL;		/* 冷却总管回水流速                Mapped at index 0x200A, subindex 0x08 */
extern INTEGER16 Sensor_OutT;		/*                                 Mapped at index 0x200A, subindex 0x09 */
extern INTEGER16 Sensor_OutH;		/*                                 Mapped at index 0x200A, subindex 0x0A */

extern UNS16 Energy_DayW;		    /* 系统当天总耗电量                Mapped at index 0x200B, subindex 0x01 */
extern UNS16 Energy_TotalP;		    /* 系统总功率                      Mapped at index 0x200B, subindex 0x02 */
extern UNS16 Energy_DayEERs;		    /* 系统当天能效比                  Mapped at index 0x200B, subindex 0x03 */
extern UNS16 Energy_MonthEERs;		/* 系统当月能效比                  Mapped at index 0x200B, subindex 0x04 */
extern UNS16 Energy_YearEERs;		/* 系统当年能效比                  Mapped at index 0x200B, subindex 0x05 */
extern UNS16 Energy_RealEERs;		/* 系统实时能效比                  Mapped at index 0x200B, subindex 0x06 */
extern UNS16 Energy_TotalEERs;		/* 系统总能效比                    Mapped at index 0x200B, subindex 0x07 */

extern UNS16 Energy_CHWF;		    /* 冷冻总管流量                    Mapped at index 0x200B, subindex 0x08 */
extern UNS32 Energy_MonthW;		    /* 系统当月总耗电量                Mapped at index 0x200B, subindex 0x09 */
extern UNS32 Energy_YearW;		    /* 系统当年总耗电量                Mapped at index 0x200B, subindex 0x0A */
extern UNS32 Energy_TotalW;		    /* 系统总耗电量                    Mapped at index 0x200B, subindex 0x0B */
extern UNS32 Energy_RealE;		    /* 系统实时制冷量                  Mapped at index 0x200B, subindex 0x0C */
extern UNS32 Energy_DayE;		    /* 系统当天制冷量                  Mapped at index 0x200B, subindex 0x0D */
extern UNS32 Energy_MonthE;		    /* 系统当月制冷量                  Mapped at index 0x200B, subindex 0x0E */
extern UNS32 Energy_YearE;		    /* 系统当年制冷量                  Mapped at index 0x200B, subindex 0x0F */
extern UNS32 Energy_TotalE;		    /* 系统总制冷量                    Mapped at index 0x200B, subindex 0x10 */
extern UNS16 Energy_CWF;		    /* 冷却总管流量                    Mapped at index 0x200B, subindex 0x11 */

extern UNS8 RunCnt_CHReal;		    /* 机组实际运行数                  Mapped at index 0x200C, subindex 0x01 */
extern UNS8 RunCnt_CHPlan;		    /* 机组计划运行数                  Mapped at index 0x200C, subindex 0x02 */
extern UNS8 RunCnt_CHRemain;		/* 机组剩余可运行数                Mapped at index 0x200C, subindex 0x03 */
extern UNS8 RunCnt_CHWPReal;		/* 冷冻泵实际运行数                Mapped at index 0x200C, subindex 0x04 */
extern UNS8 RunCnt_CHWPPlan;		/* 冷冻泵计划运行数                Mapped at index 0x200C, subindex 0x05 */
extern UNS8 RunCnt_CHWPRemain;		/* 冷冻泵剩余可运行数              Mapped at index 0x200C, subindex 0x06 */
extern UNS8 RunCnt_CWPReal;		    /* 冷却泵实际运行数                Mapped at index 0x200C, subindex 0x07 */
extern UNS8 RunCnt_CWPPlan;		    /* 冷却泵计划运行数                Mapped at index 0x200C, subindex 0x08 */
extern UNS8 RunCnt_CWPRemain;		/* 冷却泵剩余可运行数              Mapped at index 0x200C, subindex 0x09 */
extern UNS8 RunCnt_CTFReal;		    /* 冷却塔风机实际运行数            Mapped at index 0x200C, subindex 0x0A */
extern UNS8 RunCnt_CTFPlan;		    /* 冷却塔风机计划运行数            Mapped at index 0x200C, subindex 0x0B */
extern UNS8 RunCnt_CTFRemain;		/* 冷却塔风机剩余可运行数          Mapped at index 0x200C, subindex 0x0C */
extern UNS8 RunCnt_CHWV;		    /* 冷冻侧阀门开启数量             Mapped at index 0x200C, subindex 0x0D */
extern UNS8 RunCnt_CWV;		        /* 冷却侧阀门开启数量             Mapped at index 0x200C, subindex 0x0E */
extern UNS8 RunCnt_CTV;		        /* 冷却塔阀门开启数量             Mapped at index 0x200C, subindex 0x0F */

extern UNS8 SysFlags_s;		        /* 一些系统控制标志位             Mapped at index 0x200D, subindex 0x01 */
extern UNS16 Ctrl_Board1;		    /* 1#控制器控制命令               Mapped at index 0x200E, subindex 0x01 */       
extern UNS16 Ctrl_Board2;		    /* 2#控制器控制命令               Mapped at index 0x200E, subindex 0x02 */
extern UNS16 Ctrl_Board3;	        /* 3#控制器控制命令               Mapped at index 0x200E, subindex 0x03 */
extern UNS16 Ctrl_Board4;		    /* 4#控制器控制命令               Mapped at index 0x200E, subindex 0x04 */

extern UNS16 Set_CHWPFq;		    /* 冷冻水泵频率设置               Mapped at index 0x200F, subindex 0x01 */
extern UNS16 Set_CWPFq;		        /* 冷却水泵频率设置               Mapped at index 0x200F, subindex 0x02 */
extern UNS16 Set_CTFFq;		        /* 冷却塔风机频率设置             Mapped at index 0x200F, subindex 0x03 */
extern UNS16 Set_CHWBPVOC;		    /* 冷冻侧压差旁通阀开度设定        Mapped at index 0x200F, subindex 0x04 */
extern UNS16 Set_CWBPVOC;		    /* 冷却侧压差旁通阀开度设定        Mapped at index 0x200F, subindex 0x05 */

extern UNS8 Maker_Logic;		    /* 厂家开关量参数                 Mapped at index 0x2010, subindex 0x01 */
extern UNS8 Maker_CHWOTSP;		    /* 冷冻总管出水温度设定值          Mapped at index 0x2010, subindex 0x02 */
extern UNS16 Maker_CHWDPSP;		    /* 冷冻总管压差设定值             Mapped at index 0x2010, subindex 0x03 */
extern UNS8 Maker_BLoadSet;		    /* 大冷量负荷设定                 Mapped at index 0x2010, subindex 0x04 */
extern UNS8 Maker_SLoadSet;		    /* 小冷量负荷设定                 Mapped at index 0x2010, subindex 0x05 */
extern UNS8 Maker_CHWDTSP;		    /* 冷冻总管温差设定值             Mapped at index 0x2010, subindex 0x06 */
extern UNS8 Maker_CWDTSP;		    /* 冷却总管温差设定值             Mapped at index 0x2010, subindex 0x07 */
extern UNS8 Maker_CWTDownRate;		/* 冷却回水温降率设定值            Mapped at index 0x2010, subindex 0x08 */
extern UNS8 Maker_CWTUpRate;		/* 冷却回水温升率设定值            Mapped at index 0x2010, subindex 0x09 */
extern UNS8 Maker_CHWTDownRate;		/* 冷冻回水温降率设定值            Mapped at index 0x2010, subindex 0x0A */
extern UNS8 Maker_CHWDPOffset;		/* 冷冻压差偏差百分比              Mapped at index 0x2010, subindex 0x0B */
extern UNS8 Maker_CHAddLoad;		/* 加机负荷设定值                  Mapped at index 0x2010, subindex 0x0C */
extern UNS8 Maker_CHWBPVCtrlDeg;	/* 冷冻旁通阀调节幅度              Mapped at index 0x2010, subindex 0x0D */
extern UNS8 Maker_CHWBPVMax;		/* 冷冻旁通阀最大开度              Mapped at index 0x2010, subindex 0x0E */
extern UNS8 Maker_CHWBPVMin;		/* 冷冻旁通阀最小开度              Mapped at index 0x2010, subindex 0x0F */
extern UNS16 Maker_CHWBPVCtrlDly;	/* 冷冻旁通阀调节时间              Mapped at index 0x2010, subindex 0x10 */
extern UNS8 Maker_CWBPVCtrlDeg;		/* 冷却旁通阀调节幅度              Mapped at index 0x2010, subindex 0x11 */
extern UNS8 Maker_CWBPVMax;		    /* 冷却旁通阀最大开度              Mapped at index 0x2010, subindex 0x12 */
extern UNS8 Maker_CWBPVMin;		    /* 冷却旁通阀最小开度              Mapped at index 0x2010, subindex 0x13 */
extern UNS16 Maker_CWBPVCtrlDly;	/* 冷却旁通阀调节时间              Mapped at index 0x2010, subindex 0x14 */
extern UNS8 Maker_CWBPTOffset;		/* 冷却旁通温度偏差                Mapped at index 0x2010, subindex 0x15 */
extern UNS16 Maker_CWRTProLimit;	/* 机组冷却回水温度保护值           Mapped at index 0x2010, subindex 0x16 */
extern UNS16 Maker_CHStartTemp;		/* 机组冷却回水温度启动下限         Mapped at index 0x2010, subindex 0x17 */
extern UNS16 Maker_CHAddTimSlot;    /* 加机组时间间隔                  Mapped at index 0x2010, subindex 0x18 */
extern UNS16 Maker_CHSubTimSlot;    /* 减机组时间间隔                  Mapped at index 0x2010, subindex 0x19 */

extern UNS8 Maker_CHAdd1Load;		/* 1台加机组负荷设定值             Mapped at index 0x2010, subindex 0x1A */
extern UNS8 Maker_CHAdd2Load;		/* 2台加机组负荷设定值             Mapped at index 0x2010, subindex 0x1B */
extern UNS8 Maker_CHAdd3Load;		/* 3台加机组负荷设定值             Mapped at index 0x2010, subindex 0x1C */
extern UNS8 Maker_CHSub2Load;		/* 2台减机组负荷设定值             Mapped at index 0x2010, subindex 0x1D */
extern UNS8 Maker_CHSub3Load;	    /* 3台减机组负荷设定值             Mapped at index 0x2010, subindex 0x1E */
extern UNS8 Maker_CHSub4Load;		/* 4台减机组负荷设定值             Mapped at index 0x2010, subindex 0x1F */

extern INTEGER8 Maker_CHAddTOffset;     /* 加机组温度偏差值                Mapped at index 0x2010, subindex 0x20 */
extern INTEGER8 Maker_CHSubTOffset;	    /* 减机组温度偏差值                Mapped at index 0x2010, subindex 0x21 */
extern UNS16 Maker_SubCHWOffDly;		/* 减机冷冻侧设备关闭延迟           Mapped at index 0x2010, subindex 0x22 */
extern UNS16 Maker_SubCWOffDly;		    /* 减机冷却侧设备关闭延迟           Mapped at index 0x2010, subindex 0x23 */

extern UNS8 Maker_CHWPTOffset1;		    /* 冷冻泵调节温度偏差1             Mapped at index 0x2010, subindex 0x24 */
extern UNS8 Maker_CHWPTOffset2;		    /* 冷冻泵调节温度偏差2             Mapped at index 0x2010, subindex 0x25 */
extern UNS8 Maker_CHWPStartFq;		    /* 冷冻变频水泵启动频率            Mapped at index 0x2010, subindex 0x26 */
extern UNS8 Maker_CHWPMaxFq;		    /* 冷冻变频水泵最大频率            Mapped at index 0x2010, subindex 0x27 */
extern UNS8 Maker_CHWPMinFq;		    /* 冷冻变频水泵最小频率            Mapped at index 0x2010, subindex 0x28 */
extern UNS16 Maker_CHWPFqCtrlDly;		/* 冷冻泵频率调节时间              Mapped at index 0x2010, subindex 0x29 */
extern UNS16 Maker_CHWPStopDly;		    /* 冷冻泵延迟关闭时间              Mapped at index 0x2010, subindex 0x2A */
extern UNS16 Maker_CHWPStartDly;		/* 冷冻泵延迟开启时间              Mapped at index 0x2010, subindex 0x2B */
  
extern UNS8 Maker_CWPTOffset1;		    /* 冷却泵调节温度偏差1             Mapped at index 0x2010, subindex 0x2C */
extern UNS8 Maker_CWPTOffset2;		    /* 冷却泵调节温度偏差2             Mapped at index 0x2010, subindex 0x2D */
extern UNS8 Maker_CWPStartFq;		    /* 冷却变频水泵启动频率            Mapped at index 0x2010, subindex 0x2E */
extern UNS8 Maker_CWPMaxFq;		        /* 冷却变频水泵最大频率            Mapped at index 0x2010, subindex 0x2F */
extern UNS8 Maker_CWPMinFq;		        /* 冷却变频水泵最小频率            Mapped at index 0x2010, subindex 0x30 */
extern UNS16 Maker_CWPFqCtrlDly;		/* 冷却泵频率调节时间              Mapped at index 0x2010, subindex 0x31 */
extern UNS16 Maker_CWPStopDly;		    /* 冷却泵延迟关闭时间              Mapped at index 0x2010, subindex 0x32 */
extern UNS16 Maker_CWPStartDly;		    /* 冷却泵延迟开启时间              Mapped at index 0x2010, subindex 0x33 */
 
extern UNS8 Maker_CHWPAddFqDeg1;		/* 冷冻泵升频幅度1                Mapped at index 0x2010, subindex 0x34 */
extern UNS8 Maker_CHWPSubFqDeg1;		/* 冷冻泵降频幅度1                Mapped at index 0x2010, subindex 0x35 */
extern UNS8 Maker_CWPAddFqDeg1;		    /* 冷却泵升频幅度1                Mapped at index 0x2010, subindex 0x36 */
extern UNS8 Maker_CWPSubFqDeg1;		    /* 冷却泵降频幅度1                Mapped at index 0x2010, subindex 0x37 */
extern UNS8 Maker_TFStartFq;		    /* 风机变频启动频率               Mapped at index 0x2010, subindex 0x38 */
extern UNS8 Maker_TFMaxFq;		        /* 风机变频最大频率               Mapped at index 0x2010, subindex 0x39 */
extern UNS8 Maker_TFMinFq;		        /* 风机变频最小频率               Mapped at index 0x2010, subindex 0x3A */

extern UNS16 Maker_TFSubFqTemp1;		/* 风机降频温度1                 Mapped at index 0x2010, subindex 0x3B */
extern UNS16 Maker_TFSubFqTemp2;		/* 风机降频温度2                 Mapped at index 0x2010, subindex 0x3C */
extern UNS16 Maker_TFAddFqTemp1;		/* 风机升频温度1                 Mapped at index 0x2010, subindex 0x3D */
extern UNS16 Maker_TFAddFqTemp2;		/* 风机升频温度2                 Mapped at index 0x2010, subindex 0x3E */
extern UNS8 Maker_TFAddFqDeg1;		    /* 风机升频幅度1                 Mapped at index 0x2010, subindex 0x3F */
extern UNS8 Maker_TFAddFqDeg2;		    /* 风机升频幅度2                 Mapped at index 0x2010, subindex 0x40 */
extern UNS8 Maker_TFSubFqDeg1;		    /* 风机降频幅度1                 Mapped at index 0x2010, subindex 0x41 */
extern UNS8 Maker_TFSubFqDeg2;		    /* 风机降频幅度2                 Mapped at index 0x2010, subindex 0x42 */
extern UNS16 Maker_TFStartTemp;		    /* 风机启动温度值                Mapped at index 0x2010, subindex 0x43 */
 
extern UNS16 Maker_TFAddDly;		    /* 加风机延迟开启时间            Mapped at index 0x2010, subindex 0x44 */
extern UNS16 Maker_TFSubDly;		    /* 减风机延迟关闭时间            Mapped at index 0x2010, subindex 0x45 */
extern UNS16 Maker_TFAddFqDly;		    /* 风机升频率调节时间            Mapped at index 0x2010, subindex 0x46 */
extern UNS16 Maker_TFSubFqDly;		    /* 风机降频率调节时间            Mapped at index 0x2010, subindex 0x47 */
extern UNS16 Maker_TFStopDly;		    /* 风机延迟关闭时间              Mapped at index 0x2010, subindex 0x48 */
extern UNS16 Maker_TFStartDly;		    /* 风机延时开启时间              Mapped at index 0x2010, subindex 0x49 */

extern UNS16 Maker_TFAddRoTimSlot;	     /* 冷却塔加通道时间间隔          Mapped at index 0x2010, subindex 0x4A */
extern UNS16 Maker_TFSubRoTimSlot;       /* 冷却塔减通道时间间隔          Mapped at index 0x2010, subindex 0x4B */
extern UNS16 Maker_TFAddRoTemp;		     /* 冷却塔加通道温度设定值        Mapped at index 0x2010, subindex 0x4C */
extern UNS16 Maker_TFSubRoTemp;		     /* 冷却塔减通道温度设定值        Mapped at index 0x2010, subindex 0x4D */

extern UNS16 Maker_VFaultDly;		    /* 电动阀故障判断时间            Mapped at index 0x2010, subindex 0x4E */
extern UNS16 Maker_VCloseDly;	       	/* 电动阀延迟关闭时间            Mapped at index 0x2010, subindex 0x4F */

extern UNS8 Maker_EHeatStopTemp;		/* 电辅热关闭温度               Mapped at index 0x2010, subindex 0x50 */
extern UNS8 Maker_EHeatStartTemp;	    /* 电辅热启动温度               Mapped at index 0x2010, subindex 0x51 */
extern UNS8 Maker_EHeatTOffset;		    /* 电辅热温度偏差               Mapped at index 0x2010, subindex 0x52 */
extern UNS16 Maker_EHeatStartDly;		/* 电辅热延时时间               Mapped at index 0x2010, subindex 0x53 */
 
extern UNS8 Maker_WhCnt;		        /* 电能表数量                   Mapped at index 0x2010, subindex 0x54 */
extern UNS16 Maker_CHWDn;		        /* 冷冻总管管径                 Mapped at index 0x2010, subindex 0x55 */
extern UNS16 Maker_CWDn;		        /* 冷却总管管径                 Mapped at index 0x2010, subindex 0x56 */
extern UNS8 Maker_HmCnt;		        /* 热量表数量                   Mapped at index 0x2010, subindex 0x57 */
extern UNS16 Maker_CWSTProLimit;		/*                             Mapped at index 0x2010, subindex 0x58 */

extern UNS16 B1State_CHLogic;		    /* 1#机组开关量状态             Mapped at index 0x2011, subindex 0x01 */
extern UNS8 B1State_CHCtrlMode;		    /* 1#机组控制模式               Mapped at index 0x2011, subindex 0x02 */
extern UNS8 B1State_CHCHWTSP;		    /* 1#机组冷冻水出水温度设定      Mapped at index 0x2011, subindex 0x03 */
extern INTEGER16 B1State_CHCHWIT;	    /* 1#机组冷冻进水温度           Mapped at index 0x2011, subindex 0x04 */
extern INTEGER16 B1State_CHCHWOT;	    /* 1#机组冷冻出水温度           Mapped at index 0x2011, subindex 0x05 */
extern INTEGER16 B1State_CHCWIT;		/* 1#机组冷却进水温度           Mapped at index 0x2011, subindex 0x06 */
extern INTEGER16 B1State_CHCWOT;		/* 1#机组冷却出水温度           Mapped at index 0x2011, subindex 0x07 */
extern UNS32 B1State_CHRuntime;		    /* 1#机组累计运行时间           Mapped at index 0x2011, subindex 0x08 */
extern UNS16 B1State_CHLoad ;		    /* 1#机组总负荷                 Mapped at index 0x2011, subindex 0x09 */

extern UNS8 B1State_CHWP1Logic;		    /* 1-1#冷冻水泵开关量状态       Mapped at index 0x2011, subindex 0x0A */
extern UNS8 B1State_CHWP2Logic;		    /* 1-2#冷冻水泵开关量状态       Mapped at index 0x2011, subindex 0x0B */
extern UNS8 B1State_CWP1Logic;		    /* 1-1#冷却水泵开关量状态       Mapped at index 0x2011, subindex 0x0C */
extern UNS8 B1State_CWP2Logic;		    /* 1-2#冷却水泵开关量状态       Mapped at index 0x2011, subindex 0x0D */
extern UNS8 B1State_TFLogic;		    /* 1#冷却塔风机开关量状态       Mapped at index 0x2011, subindex 0x0E */

extern UNS8 B1State_CHID;		        /* 1#机组ID                    Mapped at index 0x2011, subindex 0x0F */
extern UNS16 B1State_CHWP1FqSet;		/* 1-1#冷冻水泵频率设置输出     Mapped at index 0x2011, subindex 0x10 */
extern UNS16 B1State_CHWP2FqSet;		/* 1-2#冷冻水泵频率设置输出     Mapped at index 0x2011, subindex 0x11 */
extern UNS16 B1State_CWP1FqSet;		    /* 1-1#冷却水泵频率设置输出     Mapped at index 0x2011, subindex 0x12 */
extern UNS16 B1State_CWP2FqSet;		    /* 1-2#冷却水泵频率设置输出     Mapped at index 0x2011, subindex 0x13 */

extern UNS16 B1State_TFFqSet;		    /* 1#冷却塔风机频率设置输出     Mapped at index 0x2011, subindex 0x14 */
extern UNS8 B1State_CHWV;		        /* 1#冷冻侧电动蝶阀开关量状态   Mapped at index 0x2011, subindex 0x15 */
extern UNS8 B1State_CWV;		        /* 1#冷却侧电动蝶阀开关量状态   Mapped at index 0x2011, subindex 0x16 */
extern UNS8 B1State_TFV;		        /* 1#冷却塔电动蝶阀开关量状态   Mapped at index 0x2011, subindex 0x17 */
extern UNS8 B1State_CHWBPVOSP;		    /* 1#冷冻旁通蝶阀开度设置状态   Mapped at index 0x2011, subindex 0x18 */
extern UNS8 B1State_CWBPVOSP;		    /* 1#冷却旁通蝶阀开度设置状态   Mapped at index 0x2011, subindex 0x19 */
extern UNS8 B1State_ElseDevices;		/* 1#控制器其他设备状态        Mapped at index 0x2011, subindex 0x1A */

extern UNS32 B1State_CHWP1Runtime;		/* 1-1#冷冻水泵运行时间    Mapped at index 0x2011, subindex 0x1B */
extern UNS32 B1State_CHWP2Runtime;		/* 1-2#冷冻水泵运行时间    Mapped at index 0x2011, subindex 0x1C */
extern UNS32 B1State_CWP1Runtime;		/* 1-1#冷却水泵运行时间    Mapped at index 0x2011, subindex 0x1D */
extern UNS32 B1State_CWP2Runtime;		/* 1-2#冷却水泵运行时间    Mapped at index 0x2011, subindex 0x1E */
extern UNS32 B1State_TFRuntime;		    /* 1#冷却塔风机运行时间    Mapped at index 0x2011, subindex 0x1F */
extern UNS32 B1State_EHeatRuntime;		/* 1#辅助电加热运行时间    Mapped at index 0x2011, subindex 0x20 */

extern INTEGER16 B1State_CHWST;		    /* 1#冷冻总管供水温度          Mapped at index 0x2011, subindex 0x21 */
extern INTEGER16 B1State_CHWRT;		    /* 1#冷冻总管回水温度          Mapped at index 0x2011, subindex 0x22 */
extern INTEGER16 B1State_CHWSP;		    /* 1#冷冻总管供水压力          Mapped at index 0x2011, subindex 0x23 */
extern INTEGER16 B1State_CHWRP;		    /* 1#冷冻总管回水压力          Mapped at index 0x2011, subindex 0x24 */
extern INTEGER16 B1State_CWST;		    /* 1#冷却总管供水温度          Mapped at index 0x2011, subindex 0x25 */
extern INTEGER16 B1State_CWRT;		    /* 1#冷却总管回水温度          Mapped at index 0x2011, subindex 0x26 */
extern INTEGER16 B1State_CHWRFL;		/* 1#冷冻总管回水流速          Mapped at index 0x2011, subindex 0x27 */
extern INTEGER16 B1State_CWRFL;		    /* 1#冷却总管回水流速          Mapped at index 0x2011, subindex 0x28 */

extern UNS16 B2State_CHLogic;		    /* 2#机组开关量状态           Mapped at index 0x2012, subindex 0x01 */
extern UNS8 B2State_CHCtrlMode;		    /* 2#机组控制模式             Mapped at index 0x2012, subindex 0x02 */
extern UNS8 B2State_CHCHWTSP;		    /* 2#机组冷冻水出水温度设定    Mapped at index 0x2012, subindex 0x03 */
extern INTEGER16 B2State_CHCHWIT;	    /* 2#机组冷冻进水温度         Mapped at index 0x2012, subindex 0x04 */
extern INTEGER16 B2State_CHCHWOT;	    /* 2#机组冷冻出水温度         Mapped at index 0x2012, subindex 0x05 */
extern INTEGER16 B2State_CHCWIT;		/* 2#机组冷却进水温度         Mapped at index 0x2012, subindex 0x06 */
extern INTEGER16 B2State_CHCWOT;		/* 2#机组冷却出水温度         Mapped at index 0x2012, subindex 0x07 */

extern UNS32 B2State_CHRuntime;		    /* 2#机组累计运行时间         Mapped at index 0x2012, subindex 0x08 */
extern UNS16 B2State_CHLoad;		    /* 2#机组总负荷              Mapped at index 0x2012, subindex 0x09 */
extern UNS8 B2State_CHWP1Logic;		    /* 2-1#冷冻水泵开关量状态     Mapped at index 0x2012, subindex 0x0A */
extern UNS8 B2State_CHWP2Logic;		    /* 2-2#冷冻水泵开关量状态     Mapped at index 0x2012, subindex 0x0B */
extern UNS8 B2State_CWP1Logic;		    /* 2-1#冷却水泵开关量状态     Mapped at index 0x2012, subindex 0x0C */
extern UNS8 B2State_CWP2Logic;		    /* 2-2#冷却水泵开关量状态     Mapped at index 0x2012, subindex 0x0D */
extern UNS8 B2State_TFLogic;		    /* 2#冷却塔风机开关量状态     Mapped at index 0x2012, subindex 0x0E */

extern UNS8 B2State_CHID;		        /* 2#机组ID                   Mapped at index 0x2012, subindex 0x0F */
extern UNS16 B2State_CHWP1FqSet;		/* 2-1#冷冻水泵频率设置输出    Mapped at index 0x2012, subindex 0x10 */
extern UNS16 B2State_CHWP2FqSet;		/* 2-2#冷冻水泵频率设置输出    Mapped at index 0x2012, subindex 0x11 */
extern UNS16 B2State_CWP1FqSet;		    /* 2-1#冷却水泵频率设置输出    Mapped at index 0x2012, subindex 0x12 */
extern UNS16 B2State_CWP2FqSet;		    /* 2-2#冷却水泵频率设置输出    Mapped at index 0x2012, subindex 0x13 */
extern UNS16 B2State_TFFqSet;		    /* 2#冷却塔风机频率设置输出    Mapped at index 0x2012, subindex 0x14 */
 
extern UNS8 B2State_CHWV;		        /* 2#冷冻侧电动蝶阀开关量状态   Mapped at index 0x2012, subindex 0x15 */
extern UNS8 B2State_CWV;		        /* 2#冷却侧电动蝶阀开关量状态   Mapped at index 0x2012, subindex 0x16 */
extern UNS8 B2State_TFV;		        /* 2#冷却塔电动蝶阀开关量状态   Mapped at index 0x2012, subindex 0x17 */
extern UNS8 B2State_CHWBPVOSP;		    /* 2#冷冻旁通蝶阀开度设置状态   Mapped at index 0x2012, subindex 0x18 */
extern UNS8 B2State_CWBPVOSP;		    /* 2#冷却旁通蝶阀开度设置状态   Mapped at index 0x2012, subindex 0x19 */
extern UNS8 B2State_ElseDevices;		/* 2#控制器其他设备状态        Mapped at index 0x2012, subindex 0x1A */

extern UNS32 B2State_CHWP1Runtime;		/* 2-1#冷冻水泵运行时间    Mapped at index 0x2012, subindex 0x1B */
extern UNS32 B2State_CHWP2Runtime;		/* 2-2#冷冻水泵运行时间    Mapped at index 0x2012, subindex 0x1C */
extern UNS32 B2State_CWP1Runtime;		/* 2-1#冷却水泵运行时间    Mapped at index 0x2012, subindex 0x1D */
extern UNS32 B2State_CWP2Runtime;		/* 2-2#冷却水泵运行时间    Mapped at index 0x2012, subindex 0x1E */
extern UNS32 B2State_TFRuntime;		    /* 2#冷却塔风机运行时间    Mapped at index 0x2012, subindex 0x1F */
extern UNS32 B2State_EHeatRuntime;		/* 2#辅助电加热运行时间    Mapped at index 0x2012, subindex 0x20 */

extern INTEGER16 B2State_CHWST;		    /* 2#冷冻总管供水温度          Mapped at index 0x2012, subindex 0x21 */
extern INTEGER16 B2State_CHWRT;		    /* 2#冷冻总管回水温度          Mapped at index 0x2012, subindex 0x22 */
extern INTEGER16 B2State_CHWSP;		    /* 2#冷冻总管供水压力          Mapped at index 0x2012, subindex 0x23 */
extern INTEGER16 B2State_CHWRP;		    /* 2#冷冻总管回水压力          Mapped at index 0x2012, subindex 0x24 */
extern INTEGER16 B2State_CWST;		    /* 2#冷却总管供水温度          Mapped at index 0x2012, subindex 0x25 */
extern INTEGER16 B2State_CWRT;		    /* 2#冷却总管回水温度          Mapped at index 0x2012, subindex 0x26 */
extern INTEGER16 B2State_CHWRFL;		/* 2#冷冻总管回水流速          Mapped at index 0x2012, subindex 0x27 */
extern INTEGER16 B2State_CWRFL;		    /* 2#冷却总管回水流速          Mapped at index 0x2012, subindex 0x28 */

extern UNS16 B3State_CHLogic;		    /* 3#机组开关量状态           Mapped at index 0x2013, subindex 0x01 */
extern UNS8 B3State_CHCtrlMode;		    /* 3#机组控制模式             Mapped at index 0x2013, subindex 0x02 */
extern UNS8 B3State_CHCHWTSP;		    /* 3#机组冷冻水出水温度设定    Mapped at index 0x2013, subindex 0x03 */
extern INTEGER16 B3State_CHCHWIT;	    /* 3#机组冷冻进水温度         Mapped at index 0x2013, subindex 0x04 */
extern INTEGER16 B3State_CHCHWOT;	    /* 3#机组冷冻出水温度         Mapped at index 0x2013, subindex 0x05 */
extern INTEGER16 B3State_CHCWIT;		/* 3#机组冷却进水温度         Mapped at index 0x2013, subindex 0x06 */
extern INTEGER16 B3State_CHCWOT;		/* 3#机组冷却出水温度         Mapped at index 0x2013, subindex 0x07 */

extern UNS32 B3State_CHRuntime;		    /* 3#机组累计运行时间         Mapped at index 0x2013, subindex 0x08 */
extern UNS16 B3State_CHLoad;		    /* 3#机组总负荷              Mapped at index 0x2013, subindex 0x09 */
extern UNS8 B3State_CHWP1Logic;		    /* 3-1#冷冻水泵开关量状态     Mapped at index 0x2013, subindex 0x0A */
extern UNS8 B3State_CHWP2Logic;		    /* 3-2#冷冻水泵开关量状态     Mapped at index 0x2013, subindex 0x0B */
extern UNS8 B3State_CWP1Logic;		    /* 3-1#冷却水泵开关量状态     Mapped at index 0x2013, subindex 0x0C */
extern UNS8 B3State_CWP2Logic;		    /* 3-2#冷却水泵开关量状态     Mapped at index 0x2013, subindex 0x0D */
extern UNS8 B3State_TFLogic;		    /* 3#冷却塔风机开关量状态     Mapped at index 0x2013, subindex 0x0E */

extern UNS8 B3State_CHID;		        /* 3#机组ID                   Mapped at index 0x2013, subindex 0x0F */
extern UNS16 B3State_CHWP1FqSet;		/* 3-1#冷冻水泵频率设置输出    Mapped at index 0x2013, subindex 0x10 */
extern UNS16 B3State_CHWP2FqSet;		/* 3-2#冷冻水泵频率设置输出    Mapped at index 0x2013, subindex 0x11 */
extern UNS16 B3State_CWP1FqSet;		    /* 3-1#冷却水泵频率设置输出    Mapped at index 0x2013, subindex 0x12 */
extern UNS16 B3State_CWP2FqSet;		    /* 3-2#冷却水泵频率设置输出    Mapped at index 0x2013, subindex 0x13 */
extern UNS16 B3State_TFFqSet;		    /* 3#冷却塔风机频率设置输出    Mapped at index 0x2013, subindex 0x14 */

extern UNS8 B3State_CHWV;		        /* 3#冷冻侧电动蝶阀开关量状态  Mapped at index 0x2013, subindex 0x15 */
extern UNS8 B3State_CWV;		        /* 3#冷却侧电动蝶阀开关量状态  Mapped at index 0x2013, subindex 0x16 */
extern UNS8 B3State_TFV;		        /* 3#冷却塔电动蝶阀开关量状态  Mapped at index 0x2013, subindex 0x17 */
extern UNS8 B3State_CHWBPVOSP;		    /* 3#冷冻旁通蝶阀开度设置状态  Mapped at index 0x2013, subindex 0x18 */
extern UNS8 B3State_CWBPVOSP;		    /* 3#冷却旁通蝶阀开度设置状态  Mapped at index 0x2013, subindex 0x19 */
extern UNS8 B3State_ElseDevices;		/* 3#控制器其他设备状态       Mapped at index 0x2013, subindex 0x1A */

extern UNS32 B3State_CHWP1Runtime;		/* 3-1#冷冻水泵运行时间   Mapped at index 0x2013, subindex 0x1B */
extern UNS32 B3State_CHWP2Runtime;		/* 3-2#冷冻水泵运行时间   Mapped at index 0x2013, subindex 0x1C */
extern UNS32 B3State_CWP1Runtime;		/* 3-1#冷却水泵运行时间   Mapped at index 0x2013, subindex 0x1D */
extern UNS32 B3State_CWP2Runtime;		/* 3-2#冷却水泵运行时间   Mapped at index 0x2013, subindex 0x1E */
extern UNS32 B3State_TFRuntime;		    /* 3#冷却塔风机运行时间   Mapped at index 0x2013, subindex 0x1F */
extern UNS32 B3State_EHeatRuntime;		/* 3#辅助电加热运行时间   Mapped at index 0x2013, subindex 0x20 */

extern INTEGER16 B3State_CHWST;		    /* 3#冷冻总管供水温度        Mapped at index 0x2013, subindex 0x21 */
extern INTEGER16 B3State_CHWRT;		    /* 3#冷冻总管回水温度        Mapped at index 0x2013, subindex 0x22 */
extern INTEGER16 B3State_CHWSP;		    /* 3#冷冻总管供水压力        Mapped at index 0x2013, subindex 0x23 */
extern INTEGER16 B3State_CHWRP;		    /* 3#冷冻总管回水压力        Mapped at index 0x2013, subindex 0x24 */
extern INTEGER16 B3State_CWST;		    /* 3#冷却总管供水温度        Mapped at index 0x2013, subindex 0x25 */
extern INTEGER16 B3State_CWRT;		    /* 3#冷却总管回水温度        Mapped at index 0x2013, subindex 0x26 */
extern INTEGER16 B3State_CHWRFL;		/* 3#冷冻总管回水流速        Mapped at index 0x2013, subindex 0x27 */
extern INTEGER16 B3State_CWRFL;		    /* 3#冷却总管回水流速        Mapped at index 0x2013, subindex 0x28 */
 
extern UNS16 B4State_CHLogic;		    /* 4#机组开关量状态         Mapped at index 0x2014, subindex 0x01 */
extern UNS8 B4State_CHCtrlMode;		    /* 4#机组控制模式           Mapped at index 0x2014, subindex 0x02 */
extern UNS8 B4State_CHCHWTSP;		    /* 4#机组冷冻水出水温度设定  Mapped at index 0x2014, subindex 0x03 */
extern INTEGER16 B4State_CHCHWIT;	    /* 4#机组冷冻进水温度       Mapped at index 0x2014, subindex 0x04 */
extern INTEGER16 B4State_CHCHWOT;	    /* 4#机组冷冻出水温度       Mapped at index 0x2014, subindex 0x05 */
extern INTEGER16 B4State_CHCWIT;		/* 4#机组冷却进水温度       Mapped at index 0x2014, subindex 0x06 */
extern INTEGER16 B4State_CHCWOT;		/* 4#机组冷却出水温度       Mapped at index 0x2014, subindex 0x07 */

extern UNS32 B4State_CHRuntime;		    /* 4#机组累计运行时间        Mapped at index 0x2014, subindex 0x08 */
extern UNS16 B4State_CHLoad;		    /* 4#机组总负荷             Mapped at index 0x2014, subindex 0x09 */
extern UNS8 B4State_CHWP1Logic;		    /* 4-1#冷冻水泵开关量状态    Mapped at index 0x2014, subindex 0x0A */
extern UNS8 B4State_CHWP2Logic;		    /* 4-2#冷冻水泵开关量状态    Mapped at index 0x2014, subindex 0x0B */
extern UNS8 B4State_CWP1Logic;		    /* 4-1#冷却水泵开关量状态    Mapped at index 0x2014, subindex 0x0C */
extern UNS8 B4State_CWP2Logic;		    /* 4-2#冷却水泵开关量状态    Mapped at index 0x2014, subindex 0x0D */
extern UNS8 B4State_TFLogic;		    /* 4#冷却塔风机开关量状态    Mapped at index 0x2014, subindex 0x0E */

extern UNS8 B4State_CHID;		        /* 4#机组ID                   Mapped at index 0x2014, subindex 0x0F */
extern UNS16 B4State_CHWP1FqSet;		/* 4-1#冷冻水泵频率设置输出    Mapped at index 0x2014, subindex 0x10 */
extern UNS16 B4State_CHWP2FqSet;		/* 4-2#冷冻水泵频率设置输出    Mapped at index 0x2014, subindex 0x11 */
extern UNS16 B4State_CWP1FqSet;		    /* 4-1#冷却水泵频率设置输出    Mapped at index 0x2014, subindex 0x12 */
extern UNS16 B4State_CWP2FqSet;		    /* 4-2#冷却水泵频率设置输出    Mapped at index 0x2014, subindex 0x13 */
extern UNS16 B4State_TFFqSet;		    /* 4#冷却塔风机频率设置输出    Mapped at index 0x2014, subindex 0x14 */

extern UNS8 B4State_CHWV;		        /* 4#冷冻侧电动蝶阀开关量状态   Mapped at index 0x2014, subindex 0x15 */
extern UNS8 B4State_CWV;		        /* 4#冷却侧电动蝶阀开关量状态   Mapped at index 0x2014, subindex 0x16 */
extern UNS8 B4State_TFV;		        /* 4#冷却塔电动蝶阀开关量状态   Mapped at index 0x2014, subindex 0x17 */
extern UNS8 B4State_CHWBPVOSP;		    /* 4#冷冻旁通蝶阀开度设置状态   Mapped at index 0x2014, subindex 0x18 */
extern UNS8 B4State_CWBPVOSP;		    /* 4#冷却旁通蝶阀开度设置状态   Mapped at index 0x2014, subindex 0x19 */
extern UNS8 B4State_ElseDevices;		/* 4#控制器其他设备状态        Mapped at index 0x2014, subindex 0x1A */

extern UNS32 B4State_CHWP1Runtime;		/* 4-1#冷冻水泵运行时间   Mapped at index 0x2014, subindex 0x1B */
extern UNS32 B4State_CHWP2Runtime;		/* 4-2#冷冻水泵运行时间   Mapped at index 0x2014, subindex 0x1C */
extern UNS32 B4State_CWP1Runtime;		/* 4-1#冷却水泵运行时间   Mapped at index 0x2014, subindex 0x1D */
extern UNS32 B4State_CWP2Runtime;		/* 4-2#冷却水泵运行时间   Mapped at index 0x2014, subindex 0x1E */
extern UNS32 B4State_TFRuntime;		    /* 4#冷却塔风机运行时间   Mapped at index 0x2014, subindex 0x1F */
extern UNS32 B4State_EHeatRuntime;		/* 4#辅助电加热运行时间   Mapped at index 0x2014, subindex 0x20 */

extern INTEGER16 B4State_CHWST;		/* 4#冷冻总管供水温度         Mapped at index 0x2014, subindex 0x21 */
extern INTEGER16 B4State_CHWRT;		/* 4#冷冻总管回水温度         Mapped at index 0x2014, subindex 0x22 */
extern INTEGER16 B4State_CHWSP;		/* 4#冷冻总管供水压力         Mapped at index 0x2014, subindex 0x23 */
extern INTEGER16 B4State_CHWRP;		/* 4#冷冻总管回水压力         Mapped at index 0x2014, subindex 0x24 */
extern INTEGER16 B4State_CWST;		/* 4#冷却总管供水温度         Mapped at index 0x2014, subindex 0x25 */
extern INTEGER16 B4State_CWRT;		/* 4#冷却总管回水温度         Mapped at index 0x2014, subindex 0x26 */
extern INTEGER16 B4State_CHWRFL;	/* 4#冷冻总管回水流速         Mapped at index 0x2014, subindex 0x27 */
extern INTEGER16 B4State_CWRFL;		/* 4#冷却总管回水流速         Mapped at index 0x2014, subindex 0x28 */

extern UNS16 BAState_Logic;		/* 各种辅助设备开关量状态         Mapped at index 0x2015, subindex 0x01 */
extern UNS16 BAState_OutT;		/* 室外温度                      Mapped at index 0x2015, subindex 0x02 */
extern UNS16 BAState_OutH;		/* 室外湿度                      Mapped at index 0x2015, subindex 0x03 */
extern UNS16 BAState_CHWDn;		/* 冷冻总管管径                  Mapped at index 0x2015, subindex 0x04 */
extern UNS16 BAState_CWDn;		/* 冷却总管管径                  Mapped at index 0x2015, subindex 0x05 */

extern UNS16 BAState_Wh1P;		/* 1#电表功率                    Mapped at index 0x2015, subindex 0x06 */
extern UNS16 BAState_Wh2P;		/* 2#电表功率                    Mapped at index 0x2015, subindex 0x07 */
extern UNS16 BAState_Wh3P;		/* 3#电表功率                    Mapped at index 0x2015, subindex 0x08 */
extern UNS16 BAState_Wh4P;		/* 4#电表功率                    Mapped at index 0x2015, subindex 0x09 */
extern UNS16 BAState_Wh5P;		/* 5#电表功率                    Mapped at index 0x2015, subindex 0x0A */
extern UNS16 BAState_Wh6P;		/* 6#电表功率                    Mapped at index 0x2015, subindex 0x0B */
extern UNS16 BAState_Wh7P;		/* 7#电表功率                    Mapped at index 0x2015, subindex 0x0C */
extern UNS16 BAState_Wh8P;		/* 8#电表功率                    Mapped at index 0x2015, subindex 0x0D */
extern UNS16 BAState_Wh9P;		/* 9#电表功率                    Mapped at index 0x2015, subindex 0x0E */
extern UNS16 BAState_Wh10P;		/* 10#电表功率                   Mapped at index 0x2015, subindex 0x0F */
extern UNS16 BAState_Wh11P;		/* 11#电表功率                   Mapped at index 0x2015, subindex 0x10 */
extern UNS16 BAState_Wh12P;		/* 12#电表功率                   Mapped at index 0x2015, subindex 0x11 */
extern UNS16 BAState_Wh13P;		/* 13#电表功率                   Mapped at index 0x2015, subindex 0x12 */
extern UNS16 BAState_Wh14P;		/* 14#电表功率                   Mapped at index 0x2015, subindex 0x13 */
extern UNS16 BAState_Wh15P;		/* 15#电表功率                   Mapped at index 0x2015, subindex 0x14 */
extern UNS16 BAState_Wh16P;		/* 16#电表功率                   Mapped at index 0x2015, subindex 0x15 */
extern UNS16 BAState_Wh17P;		/* 17#电表功率                   Mapped at index 0x2015, subindex 0x16 */
extern UNS16 BAState_Wh18P;		/* 18#电表功率                   Mapped at index 0x2015, subindex 0x17 */
extern UNS16 BAState_Wh19P;		/* 19#电表功率                   Mapped at index 0x2015, subindex 0x18 */
extern UNS16 BAState_Wh20P;		/* 20#电表功率                   Mapped at index 0x2015, subindex 0x19 */

extern UNS32 BAState_Wh1W;		/* 1#电表电量                    Mapped at index 0x2015, subindex 0x1A */
extern UNS32 BAState_Wh2W;		/* 2#电表电量                    Mapped at index 0x2015, subindex 0x1B */
extern UNS32 BAState_Wh3W;		/* 3#电表电量                    Mapped at index 0x2015, subindex 0x1C */
extern UNS32 BAState_Wh4W;		/* 4#电表电量                    Mapped at index 0x2015, subindex 0x1D */
extern UNS32 BAState_Wh5W;		/* 5#电表电量                    Mapped at index 0x2015, subindex 0x1E */
extern UNS32 BAState_Wh6W;		/* 6#电表电量                    Mapped at index 0x2015, subindex 0x1F */
extern UNS32 BAState_Wh7W;		/* 7#电表电量                    Mapped at index 0x2015, subindex 0x20 */
extern UNS32 BAState_Wh8W;		/* 8#电表电量                    Mapped at index 0x2015, subindex 0x21 */
extern UNS32 BAState_Wh9W;		/* 9#电表电量                    Mapped at index 0x2015, subindex 0x22 */
extern UNS32 BAState_Wh10W;		/* 10#电表电量                   Mapped at index 0x2015, subindex 0x23 */
extern UNS32 BAState_Wh11W;		/* 11#电表电量                   Mapped at index 0x2015, subindex 0x24 */
extern UNS32 BAState_Wh12W;		/* 12#电表电量                   Mapped at index 0x2015, subindex 0x25 */
extern UNS32 BAState_Wh13W;		/* 13#电表电量                   Mapped at index 0x2015, subindex 0x26 */
extern UNS32 BAState_Wh14W;		/* 14#电表电量                   Mapped at index 0x2015, subindex 0x27 */
extern UNS32 BAState_Wh15W;		/* 15#电表电量                   Mapped at index 0x2015, subindex 0x28 */
extern UNS32 BAState_Wh16W;		/* 16#电表电量                   Mapped at index 0x2015, subindex 0x29 */
extern UNS32 BAState_Wh17W;		/* 17#电表电量                   Mapped at index 0x2015, subindex 0x2A */
extern UNS32 BAState_Wh18W;		/* 18#电表电量                   Mapped at index 0x2015, subindex 0x2B */
extern UNS32 BAState_Wh19W;		/* 19#电表电量                   Mapped at index 0x2015, subindex 0x2C */
extern UNS32 BAState_Wh20W;		/* 20#电表电量                   Mapped at index 0x2015, subindex 0x2D */

extern UNS16 BAState_Hm1RealC;		/* 1#热量表实时制冷量         Mapped at index 0x2015, subindex 0x2E */
extern UNS16 BAState_Hm1RealF;		/* 1#热量表实时流量           Mapped at index 0x2015, subindex 0x2F */
extern UNS16 BAState_Hm2RealC;		/* 2#热量表实时制冷量         Mapped at index 0x2015, subindex 0x30 */
extern UNS16 BAState_Hm2RealF;		/* 2#热量表实时流量           Mapped at index 0x2015, subindex 0x31 */
extern UNS16 BAState_Hm3RealC;		/* 3#热量表实时制冷量         Mapped at index 0x2015, subindex 0x32 */
extern UNS16 BAState_Hm3RealF;		/* 3#热量表实时流量           Mapped at index 0x2015, subindex 0x33 */
extern UNS16 BAState_Hm4RealC;		/* 4#热量表实时制冷量         Mapped at index 0x2015, subindex 0x34 */
extern UNS16 BAState_Hm4RealF;		/* 4#热量表实时流量           Mapped at index 0x2015, subindex 0x35 */
extern UNS32 BAState_Hm1TotalC;		/* 1#热量表总制冷量           Mapped at index 0x2015, subindex 0x36 */
extern UNS32 BAState_Hm1TotalF;		/* 1#热量表总流量             Mapped at index 0x2015, subindex 0x37 */
extern UNS32 BAState_Hm2TotalC;		/* 2#热量表总制冷量           Mapped at index 0x2015, subindex 0x38 */
extern UNS32 BAState_Hm2TotalF;		/* 2#热量表总流量             Mapped at index 0x2015, subindex 0x39 */
extern UNS32 BAState_Hm3TotalC;		/* 3#热量表总制冷量           Mapped at index 0x2015, subindex 0x3A */
extern UNS32 BAState_Hm3TotalF;		/* 3#热量表总流量             Mapped at index 0x2015, subindex 0x3B */
extern UNS32 BAState_Hm4TotalC;		/* 4#热量表总制冷量           Mapped at index 0x2015, subindex 0x3C */
extern UNS32 BAState_Hm4TotalF;		/* 4#热量表总流量             Mapped at index 0x2015, subindex 0x3D */

extern UNS8 B1Maker_SysType;		/* 1#控制器水系统类型         Mapped at index 0x5000, subindex 0x01 */
extern UNS16 B1Maker_CHSize;		/* 1#机组制冷量设置           Mapped at index 0x5000, subindex 0x02 */
extern UNS8 B1Maker_CHAddr;		    /* 1#机组通讯地址             Mapped at index 0x5000, subindex 0x03 */
extern UNS8 B1Maker_CHWhAddr;		/* 1#机组电表地址             Mapped at index 0x5000, subindex 0x04 */
extern UNS8 B1Maker_BPVType;	    /* 1#旁通阀                  Mapped at index 0x5000, subindex 0x05 */
extern UNS8 B1Maker_CHWP1Type;		/* 1-1#冷冻水泵              Mapped at index 0x5000, subindex 0x06 */
extern UNS8 B1Maker_CHWP1WhAddr;    /* 1-1#冷冻水泵电表地址       Mapped at index 0x5000, subindex 0x07 */
extern UNS8 B1Maker_CHWP2Type;		/* 1-2#冷冻水泵              Mapped at index 0x5000, subindex 0x08 */
extern UNS8 B1Maker_CHWP2WhAddr;	/* 1-2#冷冻水泵电表地址       Mapped at index 0x5000, subindex 0x09 */
extern UNS8 B1Maker_CWP1Type;		/* 1-1#冷却水泵              Mapped at index 0x5000, subindex 0x0A */
extern UNS8 B1Maker_CWP1WhAddr;		/* 1-1#冷却水泵电表地址       Mapped at index 0x5000, subindex 0x0B */
extern UNS8 B1Maker_CWP2Type;		/* 1-2#冷却水泵              Mapped at index 0x5000, subindex 0x0C */
extern UNS8 B1Maker_CWP2WhAddr;		/* 1-2#冷却水泵电表地址       Mapped at index 0x5000, subindex 0x0D */
extern UNS8 B1Maker_CTFType;		/* 1#冷却塔风机类型           Mapped at index 0x5000, subindex 0x0E */
extern UNS8 B1Maker_CTFWhAddr;		/* 1#冷却塔风机电表地址       Mapped at index 0x5000, subindex 0x0F */

extern UNS16 B1Maker_Logic;		    /* 1#控制器开关量配置值       Mapped at index 0x5000, subindex 0x10 */
extern UNS8 B1Maker_AI1Def;		    /* 1#控制器AI接口1定义        Mapped at index 0x5000, subindex 0x11 */
extern UNS8 B1Maker_AI2Def;		    /* 1#控制器AI接口2定义        Mapped at index 0x5000, subindex 0x12 */
extern UNS8 B1Maker_AI3Def;		    /* 1#控制器AI接口3定义        Mapped at index 0x5000, subindex 0x13 */
extern UNS8 B1Maker_AI4Def;		    /* 1#控制器AI接口4定义        Mapped at index 0x5000, subindex 0x14 */
extern INTEGER16 B1Maker_AI1Max;		/* 1#控制器AI接口1上限值      Mapped at index 0x5000, subindex 0x15 */
extern INTEGER16 B1Maker_AI1Min;		/* 1#控制器AI接口1下限值      Mapped at index 0x5000, subindex 0x16 */
extern INTEGER16 B1Maker_AI2Max;		/* 1#控制器AI接口2上限值      Mapped at index 0x5000, subindex 0x17 */
extern INTEGER16 B1Maker_AI2Min;		/* 1#控制器AI接口2下限值      Mapped at index 0x5000, subindex 0x18 */
extern INTEGER16 B1Maker_AI3Max;		/* 1#控制器AI接口3上限值      Mapped at index 0x5000, subindex 0x19 */
extern INTEGER16 B1Maker_AI3Min;		/* 1#控制器AI接口3下限值      Mapped at index 0x5000, subindex 0x1A */
extern INTEGER16 B1Maker_AI4Max;		/* 1#控制器AI接口4上限值      Mapped at index 0x5000, subindex 0x1B */
extern INTEGER16 B1Maker_AI4Min;		/* 1#控制器AI接口4下限值      Mapped at index 0x5000, subindex 0x1C */

extern UNS8 B2Maker_SysType;		    /* 2#控制器水系统类型         Mapped at index 0x5001, subindex 0x01 */
extern UNS16 B2Maker_CHSize;		    /* 2#机组制冷量设置           Mapped at index 0x5001, subindex 0x02 */
extern UNS8 B2Maker_CHAddr;		        /* 2#机组通讯地址             Mapped at index 0x5001, subindex 0x03 */
extern UNS8 B2Maker_CHWhAddr;		    /* 2#机组电表地址             Mapped at index 0x5001, subindex 0x04 */
extern UNS8 B2Maker_BPVType;		    /* 2#旁通阀                  Mapped at index 0x5001, subindex 0x05 */
extern UNS8 B2Maker_CHWP1Type;		    /* 2-1#冷冻水泵              Mapped at index 0x5001, subindex 0x06 */
extern UNS8 B2Maker_CHWP1WhAddr;		/* 2-1#冷冻水泵电表地址       Mapped at index 0x5001, subindex 0x07 */
extern UNS8 B2Maker_CHWP2Type;		    /* 2-2#冷冻水泵              Mapped at index 0x5001, subindex 0x08 */
extern UNS8 B2Maker_CHWP2WhAddr;		/* 2-2#冷冻水泵电表地址       Mapped at index 0x5001, subindex 0x09 */
extern UNS8 B2Maker_CWP1Type;		    /* 2-1#冷却水泵              Mapped at index 0x5001, subindex 0x0A */
extern UNS8 B2Maker_CWP1WhAddr;		    /* 2-1#冷却水泵电表地址       Mapped at index 0x5001, subindex 0x0B */
extern UNS8 B2Maker_CWP2Type;		    /* 2-2#冷却水泵              Mapped at index 0x5001, subindex 0x0C */
extern UNS8 B2Maker_CWP2WhAddr;		    /* 2-2#冷却水泵电表地址       Mapped at index 0x5001, subindex 0x0D */
extern UNS8 B2Maker_CTFType;		    /* 2#冷却塔风机              Mapped at index 0x5001, subindex 0x0E */
extern UNS8 B2Maker_CTFWhAddr;		    /* 2#冷却塔风机电表地址       Mapped at index 0x5001, subindex 0x0F */

extern UNS16 B2Maker_Logic;		        /* 2#控制器开关量配置值       Mapped at index 0x5001, subindex 0x10 */
extern UNS8 B2Maker_AI1Def;		        /* 2#控制器AI接口1定义        Mapped at index 0x5001, subindex 0x11 */
extern UNS8 B2Maker_AI2Def;		        /* 2#控制器AI接口2定义        Mapped at index 0x5001, subindex 0x12 */
extern UNS8 B2Maker_AI3Def;		        /* 2#控制器AI接口3定义        Mapped at index 0x5001, subindex 0x13 */
extern UNS8 B2Maker_AI4Def;		        /* 2#控制器AI接口4定义        Mapped at index 0x5001, subindex 0x14 */
extern INTEGER16 B2Maker_AI1Max;		/* 2#控制器AI接口1上限值      Mapped at index 0x5001, subindex 0x15 */
extern INTEGER16 B2Maker_AI1Min;		/* 2#控制器AI接口1下限值      Mapped at index 0x5001, subindex 0x16 */
extern INTEGER16 B2Maker_AI2Max;		/* 2#控制器AI接口2上限值      Mapped at index 0x5001, subindex 0x17 */
extern INTEGER16 B2Maker_AI2Min;		/* 2#控制器AI接口2下限值      Mapped at index 0x5001, subindex 0x18 */
extern INTEGER16 B2Maker_AI3Max;		/* 2#控制器AI接口3上限值      Mapped at index 0x5001, subindex 0x19 */
extern INTEGER16 B2Maker_AI3Min;	    /* 2#控制器AI接口3下限值      Mapped at index 0x5001, subindex 0x1A */
extern INTEGER16 B2Maker_AI4Max;		/* 2#控制器AI接口4上限值      Mapped at index 0x5001, subindex 0x1B */
extern INTEGER16 B2Maker_AI4Min;		/* 2#控制器AI接口4下限值      Mapped at index 0x5001, subindex 0x1C */

extern UNS8 B3Maker_SysType;		    /* 3#控制器水系统类型         Mapped at index 0x5002, subindex 0x01 */
extern UNS16 B3Maker_CHSize;		    /* 3#机组制冷量设置           Mapped at index 0x5002, subindex 0x02 */
extern UNS8 B3Maker_CHAddr;		        /* 3#机组通讯地址             Mapped at index 0x5002, subindex 0x03 */
extern UNS8 B3Maker_CHWhAddr;		    /* 3#机组电表地址             Mapped at index 0x5002, subindex 0x04 */
extern UNS8 B3Maker_BPVType;		    /* 3#旁通阀                  Mapped at index 0x5002, subindex 0x05 */
extern UNS8 B3Maker_CHWP1Type;		    /* 3-1#冷冻水泵              Mapped at index 0x5002, subindex 0x06 */
extern UNS8 B3Maker_CHWP1WhAddr;		/* 3-1#冷冻水泵电表地址       Mapped at index 0x5002, subindex 0x07 */
extern UNS8 B3Maker_CHWP2Type;		    /* 3-2#冷冻水泵              Mapped at index 0x5002, subindex 0x08 */
extern UNS8 B3Maker_CHWP2WhAddr;		/* 3-2#冷冻水泵电表地址       Mapped at index 0x5002, subindex 0x09 */
extern UNS8 B3Maker_CWP1Type;		    /* 3-1#冷却水泵              Mapped at index 0x5002, subindex 0x0A */
extern UNS8 B3Maker_CWP1WhAddr;		    /* 3-1#冷却水泵电表地址       Mapped at index 0x5002, subindex 0x0B */
extern UNS8 B3Maker_CWP2Type;		    /* 3-2#冷却水泵              Mapped at index 0x5002, subindex 0x0C */
extern UNS8 B3Maker_CWP2WhAddr;		    /* 3-2#冷却水泵电表地址       Mapped at index 0x5002, subindex 0x0D */
extern UNS8 B3Maker_CTFType;		    /* 3#冷却塔风机              Mapped at index 0x5002, subindex 0x0E */
extern UNS8 B3Maker_CTFWhAddr;		    /* 3#冷却塔风机电表地址       Mapped at index 0x5002, subindex 0x0F */

extern UNS16 B3Maker_Logic;		        /* 3#控制器开关量配置值       Mapped at index 0x5002, subindex 0x10 */
extern UNS8 B3Maker_AI1Def;		        /* 3#控制器AI接口1定义       Mapped at index 0x5002, subindex 0x11 */
extern UNS8 B3Maker_AI2Def;		        /* 3#控制器AI接口2定义       Mapped at index 0x5002, subindex 0x12 */
extern UNS8 B3Maker_AI3Def;		        /* 3#控制器AI接口3定义       Mapped at index 0x5002, subindex 0x13 */
extern UNS8 B3Maker_AI4Def;		        /* 3#控制器AI接口4定义       Mapped at index 0x5002, subindex 0x14 */
extern INTEGER16 B3Maker_AI1Max;		/* 3#控制器AI接口1上限值     Mapped at index 0x5002, subindex 0x15 */
extern INTEGER16 B3Maker_AI1Min;		/* 3#控制器AI接口1下限值     Mapped at index 0x5002, subindex 0x16 */
extern INTEGER16 B3Maker_AI2Max;		/* 3#控制器AI接口2上限值     Mapped at index 0x5002, subindex 0x17 */
extern INTEGER16 B3Maker_AI2Min;		/* 3#控制器AI接口2下限值     Mapped at index 0x5002, subindex 0x18 */
extern INTEGER16 B3Maker_AI3Max;		/* 3#控制器AI接口3上限值     Mapped at index 0x5002, subindex 0x19 */
extern INTEGER16 B3Maker_AI3Min;		/* 3#控制器AI接口3下限值     Mapped at index 0x5002, subindex 0x1A */
extern INTEGER16 B3Maker_AI4Max;		/* 3#控制器AI接口4上限值     Mapped at index 0x5002, subindex 0x1B */
extern INTEGER16 B3Maker_AI4Min;		/* 3#控制器AI接口4下限值     Mapped at index 0x5002, subindex 0x1C */

extern UNS8 B4Maker_SysType;		    /* 4#控制器水系统类型        Mapped at index 0x5003, subindex 0x01 */
extern UNS16 B4Maker_CHSize;		    /* 4#机组制冷量设置          Mapped at index 0x5003, subindex 0x02 */
extern UNS8 B4Maker_CHAddr;		        /* 4#机组通讯地址            Mapped at index 0x5003, subindex 0x03 */
extern UNS8 B4Maker_CHWhAddr;		    /* 4#机组电表地址            Mapped at index 0x5003, subindex 0x04 */
extern UNS8 B4Maker_BPVType;		    /* 4#旁通阀                 Mapped at index 0x5003, subindex 0x05 */
extern UNS8 B4Maker_CHWP1Type;		    /* 4-1#冷冻水泵             Mapped at index 0x5003, subindex 0x06 */
extern UNS8 B4Maker_CHWP1WhAddr;		/* 4-1#冷冻水泵电表地址      Mapped at index 0x5003, subindex 0x07 */
extern UNS8 B4Maker_CHWP2Type;		    /* 4-2#冷冻水泵             Mapped at index 0x5003, subindex 0x08 */
extern UNS8 B4Maker_CHWP2WhAddr;		/* 4-2#冷冻水泵电表地址      Mapped at index 0x5003, subindex 0x09 */
extern UNS8 B4Maker_CWP1Type;		    /* 4-1#冷却水泵             Mapped at index 0x5003, subindex 0x0A */
extern UNS8 B4Maker_CWP1WhAddr;		    /* 4-1#冷却水泵电表地址      Mapped at index 0x5003, subindex 0x0B */
extern UNS8 B4Maker_CWP2Type;		    /* 4-2#冷却水泵             Mapped at index 0x5003, subindex 0x0C */
extern UNS8 B4Maker_CWP2WhAddr;	    	/* 4-2#冷却水泵电表地址      Mapped at index 0x5003, subindex 0x0D */
extern UNS8 B4Maker_CTFType;		    /* 4#冷却塔风机             Mapped at index 0x5003, subindex 0x0E */
extern UNS8 B4Maker_CTFWhAddr;		    /* 4#冷却塔风机电表地址      Mapped at index 0x5003, subindex 0x0F */
    
extern UNS16 B4Maker_Logic;		        /* 4#控制器开关量配置值      Mapped at index 0x5003, subindex 0x10 */
extern UNS8 B4Maker_AI1Def;		        /* 4#控制器AI接口1定义      Mapped at index 0x5003, subindex 0x11 */
extern UNS8 B4Maker_AI2Def;		        /* 4#控制器AI接口2定义      Mapped at index 0x5003, subindex 0x12 */
extern UNS8 B4Maker_AI3Def;		        /* 4#控制器AI接口3定义      Mapped at index 0x5003, subindex 0x13 */
extern UNS8 B4Maker_AI4Def;		        /* 4#控制器AI接口4定义      Mapped at index 0x5003, subindex 0x14 */
extern INTEGER16 B4Maker_AI1Max;		/* 4#控制器AI接口1上限值    Mapped at index 0x5003, subindex 0x15 */
extern INTEGER16 B4Maker_AI1Min;		/* 4#控制器AI接口1下限值    Mapped at index 0x5003, subindex 0x16 */
extern INTEGER16 B4Maker_AI2Max;		/* 4#控制器AI接口2上限值    Mapped at index 0x5003, subindex 0x17 */
extern INTEGER16 B4Maker_AI2Min;		/* 4#控制器AI接口2下限值    Mapped at index 0x5003, subindex 0x18 */
extern INTEGER16 B4Maker_AI3Max;		/* 4#控制器AI接口3上限值    Mapped at index 0x5003, subindex 0x19 */
extern INTEGER16 B4Maker_AI3Min;		/* 4#控制器AI接口3下限值    Mapped at index 0x5003, subindex 0x1A */
extern INTEGER16 B4Maker_AI4Max;		/* 4#控制器AI接口4上限值    Mapped at index 0x5003, subindex 0x1B */
extern INTEGER16 B4Maker_AI4Min;		/* 4#控制器AI接口4下限值    Mapped at index 0x5003, subindex 0x1C */

#endif // MASTERSLAVE_H
